# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp
	pod 'Firebase/Core'
	pod 'Firebase/Storage'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'SDWebImage', '~> 5.8'
	pod 'JGProgressHUD', '~> 2.1'
end
